# ================================
# 🌱 AgriESG — Farm-Level Analysis
# ================================

import streamlit as st
import pandas as pd
import numpy as np
import altair as alt

# ---------------------------------------------------
# Streamlit Page Config (WHITE THEME)
# ---------------------------------------------------
st.set_page_config(
    page_title="AgriESG — Farm ESG Analysis",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Force white background
st.markdown(
    """
    <style>
    body, .stApp { background-color: white !important; }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------
# Emission factors
# ---------------------------------------------------
EF_N = 5.5
EF_DIESEL = 2.7
EF_ELEC = 0.5


# ---------------------------------------------------
# KPI Calculation
# ---------------------------------------------------
def compute_kpis(df):
    df = df.copy()

    df["yield_per_ha"] = df["yield_tonnes"] / df["area_ha"]
    df["n_per_ha"] = df["fertilizer_n_kg"] / df["area_ha"]
    df["water_per_tonne"] = df["water_m3"] / df["yield_tonnes"]

    emissions_fert = df["fertilizer_n_kg"] * EF_N
    emissions_diesel = df["diesel_litres"] * EF_DIESEL
    emissions_elec = df["electricity_kwh"] * EF_ELEC

    df["total_emissions"] = emissions_fert + emissions_diesel + emissions_elec
    df["emissions_per_ha"] = df["total_emissions"] / df["area_ha"]
    df["emissions_per_tonne"] = df["total_emissions"] / df["yield_tonnes"]

    df["female_share"] = df["workers_female"] / df["workers_total"]
    df["accidents_per_100_workers"] = (
        df["accidents_count"] / df["workers_total"] * 100
    )

    return df


# ---------------------------------------------------
# ESG Report Generator
# ---------------------------------------------------
def generate_esg_report(row):
    def s(x, unit=""):
        return f"{x:.2f}{unit}" if pd.notna(x) else "N/A"

    report = f"""
# 🌱 ESG Report — {row['organisation_name']} ({row['farm_id']})

## 1. Executive Summary
This ESG report provides a sustainability snapshot of **{row['organisation_name']}**, 
producing **{row['crop']}** in **{row['country']}**.

## 2. Environmental Performance

### 🌍 Carbon & Energy
- Total emissions: **{s(row['total_emissions'], ' kg CO₂e')}**
- Emissions per tonne: **{s(row['emissions_per_tonne'], ' kg CO₂e/t')}**
- Diesel use: **{s(row['diesel_litres'], ' L')}**
- Electricity use: **{s(row['electricity_kwh'], ' kWh')}**

### 💧 Water & Inputs
- Total water use: **{s(row['water_m3'], ' m³')}**
- Water per tonne: **{s(row['water_per_tonne'], ' m³/t')}**
- Nitrogen fertilizer: **{s(row['fertilizer_n_kg'], ' kg')}**

---

## 3. Social Performance
- Total workers: **{int(row['workers_total'])}**
- Female workers: **{int(row['workers_female'])}**
- Female share: **{s(row['female_share']*100, '%')}**
- Accident rate: **{s(row['accidents_per_100_workers'], ' per 100 workers')}**

---

## 4. Governance
- Certification: **{row.get('certification_scheme', 'None')}**
- Safety policy: *Not provided* (MVP)
- Grievance mechanism: *Not provided* (MVP)

---

## 5. Suggested Targets
- Reduce emissions intensity by **10% in 2 years**
- Improve water efficiency by **15% per tonne**
- Raise female participation to **30%**
- Achieve **0 accidents** per 100 workers

---

*Report auto-generated by AgriESG.*
    """

    return report


# ---------------------------------------------------
# File Upload
# ---------------------------------------------------
st.title("🌱 AgriESG — Farm-Level ESG Analysis")

uploaded = st.file_uploader("Upload your CSV file", type=["csv"])

if uploaded is None:
    st.info("Upload a CSV to begin.")
    st.stop()

df = pd.read_csv(uploaded)
df = compute_kpis(df)

# ---------------------------------------------------
# Select Farm
# ---------------------------------------------------
farm = st.selectbox("Select a farm", df["farm_id"].unique())
row = df[df["farm_id"] == farm].iloc[0]

# ---------------------------------------------------
# KPI CARDS
# ---------------------------------------------------
st.subheader("🌍 Key Performance Indicators")

k1, k2, k3, k4 = st.columns(4)

k1.metric("Yield per ha", f"{row['yield_per_ha']:.2f} t/ha")
k2.metric("Emissions per tonne", f"{row['emissions_per_tonne']:.1f} kg CO₂e/t")
k3.metric("Water per tonne", f"{row['water_per_tonne']:.1f} m³/t")
k4.metric("Female workforce", f"{row['female_share']*100:.0f} %")

# ---------------------------------------------------
# Environmental Chart
# ---------------------------------------------------
st.subheader("🌿 Environmental Indicators")

env_df = pd.DataFrame({
    "Indicator": ["N fertilizer (kg)", "Diesel (L)", "Electricity (kWh)", "Water (m³)"],
    "Value": [
        row["fertilizer_n_kg"],
        row["diesel_litres"],
        row["electricity_kwh"],
        row["water_m3"],
    ],
})

env_chart = (
    alt.Chart(env_df)
    .mark_bar()
    .encode(
        x="Indicator:N",
        y="Value:Q",
        tooltip=["Indicator", "Value"],
        color="Indicator:N"
    )
)

st.altair_chart(env_chart, use_container_width=True)

# ---------------------------------------------------
# Social Indicators (FIXED)
# ---------------------------------------------------
st.subheader("👩‍🌾 Social Indicators")

soc_df = pd.DataFrame({
    "Indicator": ["Female workforce (%)", "Accidents per 100 workers"],
    "Value": [
        row["female_share"] * 100,
        row["accidents_per_100_workers"],
    ],
})

soc_chart = (
    alt.Chart(soc_df)
    .mark_bar()
    .encode(
        x="Indicator:N",
        y="Value:Q",
        color="Indicator:N",
        tooltip=["Indicator", "Value"]
    )
)

st.altair_chart(soc_chart, use_container_width=True)

# ---------------------------------------------------
# Governance Section
# ---------------------------------------------------
st.subheader("📑 Governance")

st.write(f"**Certification:** {row.get('certification_scheme', 'None')}")

# ---------------------------------------------------
# ESG REPORT
# ---------------------------------------------------
st.subheader("📄 Auto-Generated ESG Report")

report_text = generate_esg_report(row)
st.markdown(report_text)
